<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Tasks</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="<?= $style ?>">
        <link href="https://fonts.googleapis.com/css2?family=Andika&family=Cousine&family=Roboto&display=swap" rel="stylesheet">

    </head>
    <body>
        <?= $nav->render() ?>

        <div class="content">
            <?= $body->render() ?>
            <?= $pagination->render() ?>
        </div>
        
        <script src="" async defer></script>
    </body>
</html>